version: "3.8"
services:
  training_graph_api:
    image: training_graph_api
    ports:
      - "5555:80"
    depends_on:
      - "training_db"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 5
        window: 10s
  training_db:
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "C0t3cnaTraining"
      ACCEPT_EULA: "Y"
    volumes:
      - training_db_data:/var/opt/mssql/data

volumes:
  training_db_data: