using GraphApi.Infraestructure.Entities;
using GraphQL.Types;

namespace GraphApi.GraphQLMiddleWare.Types
{
    public class ContractType : ObjectGraphType<Contract>
    {
        public ContractType()
        {
            Name = "Contract";
            Field(x => x.Id).Description("Internal contract Id");
            Field(x => x.Name).Description("Comdiv autogenerated contract name");
            Field(x => x.ContractType).Description("International or Local contract");
            Field(x => x.Operations, type: typeof(ListGraphType<OperationType>)).Description("Contract's operations");
        }
    }
    public class ContractInputType : InputObjectGraphType<Contract>
    {
        public ContractInputType()
        {
            Name = "InputContract";
            Field(x => x.Id, nullable: true).Description("Internal contract Id");
            Field(x => x.Name, nullable: true).Description("Comdiv autogenerated contract name");
            Field(x => x.ContractType, nullable: true).Description("International or Local contract");
        }
    }
}
