using GraphApi.Infraestructure.Entities;
using GraphQL.Types;

namespace GraphApi.GraphQLMiddleWare.Types
{
    public class InspectionType : ObjectGraphType<Inspection>
    {
        public InspectionType()
        {
            Name = "Inspection";
            Field(x => x.Id).Description("Internal inspection id");
            Field(x => x.Name).Description("Comdiv autogenerated name");
            Field(x => x.InspectionPlace).Description("Location where the inspection will be done");
            Field(x => x.InspectionDate).Description("Date for the inspection");
        }
    }
}
