using GraphApi.Infraestructure.Entities;
using GraphQL.Types;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GraphApi.GraphQLMiddleWare.Types
{
    public class OperationType: ObjectGraphType<Operation>
    {
        public OperationType()
        {
            Name = "Operation";
            Field(x => x.Id).Description("Internal id operation");
            Field(x => x.Number).Description("Autogenerated comdiv operation name");
            Field(x => x.Inspections, type: typeof(ListGraphType<InspectionType>)).Description("Operations' inspections");
        }
    }
}
